// pages/index.tsx
import Head from "next/head";
import styles from "@/styles/home.module.css";
import Image from "next/image";
import Modal from "../components/Modal";
import { useState } from "react";
import imgSol from "../../public/sol.png";
import imgTerra from "../../public/terra.png";
import imgMercurio from "../../public/mercurio.png";
import imgVenus from "../../public/venus.png";
import imgMarte from "../../public/marte.png";
import imgJupiter from "../../public/jupiter.png";
import imgSaturno from "../../public/saturno.png";
import imgUrano from "../../public/urano.png";
import imgNetuno from "../../public/netuno.png";

const Home: React.FC = () => {
  const [showModal, setShowModal] = useState<boolean>(false);
  const [selectedPlanet, setSelectedPlanet] = useState<string | null>(null);

  const handleImageClick = (planet: string) => {
    setSelectedPlanet(planet);
    setShowModal(true);
  };

  const handleCloseModal = () => {
    setShowModal(false);
    setSelectedPlanet(null);
  };

  return (
    <>
      <Head>
        <title>Sistema Solar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}>
        <div className={styles.sol}>
          <Image
            src={imgSol}
            alt="Sol"
            width={250}
            height={200}
            objectFit="contain"
            onClick={() => handleImageClick("Sol")}
          />
        </div>

        <div className={styles.venus}>
          <Image
            src={imgVenus}
            alt="Vênus"
            width={100}
            height={90}
            objectFit="contain"
            onClick={() => handleImageClick("Vênus")}
          />
        </div>

        <div className={styles.mercurio}>
          <Image
            src={imgMercurio}
            alt="Mercúrio"
            width={100}
            height={50}
            objectFit="contain"
            onClick={() => handleImageClick("Mercúrio")}
          />
        </div>

        <div className={styles.terra}>
          <Image
            src={imgTerra}
            alt="Terra"
            width={100}
            height={50}
            objectFit="contain"
            onClick={() => handleImageClick("Terra")}
          />
        </div>

        <div className={styles.marte}>
          <Image
            src={imgMarte}
            alt="Marte"
            width={60}
            height={40}
            objectFit="contain"
            onClick={() => handleImageClick("Marte")}
          />
        </div>

        <div className={styles.jupiter}>
          <Image
            src={imgJupiter}
            alt="Júpiter"
            width={160}
            height={90}
            objectFit="contain"
            onClick={() => handleImageClick("Júpiter")}
          />
        </div>

        <div className={styles.saturno}>
          <Image
            src={imgSaturno}
            alt="Saturno"
            width={170}
            height={70}
            objectFit="contain"
            onClick={() => handleImageClick("Saturno")}
          />
        </div>

        <div className={styles.urano}>
          <Image
            src={imgUrano}
            alt="Urano"
            width={100}
            height={50}
            objectFit="contain"
            onClick={() => handleImageClick("Urano")}
          />
        </div>

        <div className={styles.netuno}>
          <Image
            src={imgNetuno}
            alt="Netuno"
            width={100}
            height={50}
            objectFit="contain"
            onClick={() => handleImageClick("Netuno")}
          />
        </div>

        <Modal show={showModal} onClose={handleCloseModal}>
          <h2>{selectedPlanet}</h2>
          <p>Informações sobre {selectedPlanet}.</p>
        </Modal>
      </main>
    </>
  );
};

export default Home;
